<#
  Saves your Postiz API key to config/social.env and verifies the whole chain
  works: key is valid, channels are connected, and the pipeline can reach them.

  Usage:
      .\scripts\setup-postiz-key.ps1
#>

$ErrorActionPreference = "Stop"

function Info($m) { Write-Host "[*] $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "[+] $m" -ForegroundColor Green }
function Warn($m) { Write-Host "[!] $m" -ForegroundColor Yellow }
function Fail($m) { Write-Host "[x] $m" -ForegroundColor Red; exit 1 }

# Docker writes progress to stderr even on success, which would surface as a
# terminating error under ErrorActionPreference=Stop. Args are passed as ONE
# array so flags like -d aren't parsed as PowerShell parameter names.
# Call it as:  Invoke-Docker $someArray
function Invoke-Docker {
    param([string[]]$DockerArgs)

    $prev = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $output = & docker @DockerArgs 2>&1 | Out-String
        $code   = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $prev
    }
    return [pscustomobject]@{ Output = $output; ExitCode = $code }
}

# Run from the repo root regardless of where the user invoked it
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

# ── 1. Work out the backend URL from the running container ─────────────────
Info "Reading Postiz config from the running container..."

$backendUrl = "http://localhost:4007/api"
$cmd        = @('exec', 'postiz', 'env')
$envResult  = Invoke-Docker $cmd
if ($envResult.ExitCode -eq 0) {
    $match = $envResult.Output -split "`n" | Select-String "^NEXT_PUBLIC_BACKEND_URL=(.+)$"
    if ($match) {
        $backendUrl = $match.Matches[0].Groups[1].Value.Trim()
        Ok "Backend URL: $backendUrl"
    }
} else {
    Warn "Couldn't read the container env; assuming $backendUrl"
}

# ── 2. Collect the API key ─────────────────────────────────────────────────
Write-Host ""
Write-Host "In Postiz: Settings -> Public API -> Generate, then paste it here." -ForegroundColor White
Write-Host ""
$apiKey = (Read-Host "  API key").Trim()
if (-not $apiKey) { Fail "No key entered." }

# ── 3. Verify it before saving ─────────────────────────────────────────────
Info "Testing the key against $backendUrl/public/v1/integrations ..."

try {
    $resp = Invoke-RestMethod -Uri "$backendUrl/public/v1/integrations" `
                              -Headers @{ Authorization = $apiKey } `
                              -Method Get -TimeoutSec 30
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 401) { Fail "Postiz rejected that key (401). Generate a fresh one and retry." }
    Fail "Couldn't reach the Postiz API ($code). Is the container healthy? Try: docker logs postiz --tail 30"
}

# Postiz wraps the list as {"value":[...], "Count":n}; older builds returned a
# bare array. Unwrap whichever came back.
$channels = @()
if ($resp -is [array])      { $channels = $resp }
elseif ($resp.value)        { $channels = @($resp.value) }
elseif ($resp.integrations) { $channels = @($resp.integrations) }

if ($channels.Count -eq 0) {
    Warn "The key works, but no channels are connected yet."
    Warn "Open http://localhost:4007 and click 'Add Channel' first."
} else {
    Ok "Key valid. Connected channels:"
    foreach ($c in $channels) {
        $name = if ($c.name) { $c.name } else { "(unnamed)" }
        # Postiz calls the platform 'identifier'.
        $provider = @($c.identifier, $c.providerIdentifier, $c.provider |
                      Where-Object { $_ })[0]
        if (-not $provider) { $provider = "?" }
        $flag = if ($c.disabled) { "  (DISABLED)" } else { "" }
        Write-Host "      - $name  [$provider]$flag" -ForegroundColor White
    }
}

# ── 4. Save to config/social.env, preserving anything already there ─────────
$envPath = "config\social.env"
if (-not (Test-Path "config")) { New-Item -ItemType Directory -Path "config" | Out-Null }

$existing = @{}
if (Test-Path $envPath) {
    Copy-Item $envPath "$envPath.bak" -Force
    foreach ($line in Get-Content $envPath) {
        if ($line -match "^\s*([A-Z_]+)\s*=\s*(.*)$") { $existing[$Matches[1]] = $Matches[2] }
    }
}

$existing["OLLAMA_URL"]     = if ($existing.ContainsKey("OLLAMA_URL"))    { $existing["OLLAMA_URL"] }    else { "http://localhost:11434" }
$existing["CONTENT_MODEL"]  = if ($existing.ContainsKey("CONTENT_MODEL")) { $existing["CONTENT_MODEL"] } else { "llama3.2" }
$existing["POSTIZ_URL"]     = $backendUrl
$existing["POSTIZ_API_KEY"] = $apiKey

$out = @("# MuscleMap pipeline credentials - generated by setup-postiz-key.ps1", "")
foreach ($k in $existing.Keys | Sort-Object) { $out += "$k=$($existing[$k])" }
Set-Content -Path $envPath -Value $out -Encoding UTF8

Ok "Saved to $envPath"

Write-Host ""
if ($channels.Count -gt 0) {
    Write-Host "Everything's wired. Post your video with:" -ForegroundColor White
    Write-Host "  py scripts\post-to-postiz.py --file output\videos\<FILENAME>.mp4" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Or run the whole create-and-post pipeline:" -ForegroundColor White
    Write-Host "  bash scripts\nightly-pipeline.sh" -ForegroundColor Cyan
} else {
    Write-Host "Connect a channel at http://localhost:4007, then re-run this script." -ForegroundColor White
}
